const books = [
  { 
    id: '1', 
    title: 'Orgulho e Preconceito', 
    author: 'Jane Austen', 
    image: 'https://covers.openlibrary.org/b/id/5142616-L.jpg',
    description: 'Orgulho e Preconceito é um romance de Jane Austen, publicado pela primeira vez em 1813. A história segue a personagem principal, Elizabeth Bennet, enquanto ela lida com questões de maneiras, educação, moralidade, educação, e casamento na sociedade da aristocracia rural da Inglaterra do início do século XIX. Elizabeth é a segunda de cinco filhas de um cavalheiro do campo, Sr. Bennet, que mora em Longbourn.',
    genre: 'Literatura Clássica',
    publicationYear: '1813',
    language: 'Inglês',
    pageCount: 432
  },
  { 
    id: '2', 
    title: 'Moby Dick', 
    author: 'Herman Melville', 
    image: 'https://covers.openlibrary.org/b/id/7954280-L.jpg',
    description: 'Moby-Dick; ou, A Baleia é um romance de 1851 escrito pelo autor americano Herman Melville. O livro é a narrativa do marinheiro Ishmael sobre a busca obsessiva de Ahab, capitão do navio baleeiro Pequod, por vingança contra uma gigantesca baleia branca chamada Moby Dick, que em uma viagem anterior destruiu seu navio e decepou sua perna no joelho.',
    genre: 'Aventura',
    publicationYear: '1851',
    language: 'Inglês',
    pageCount: 624
  },
  { 
    id: '3', 
    title: 'As Aventuras de Sherlock Holmes', 
    author: 'Arthur Conan Doyle', 
    image: 'https://covers.openlibrary.org/b/id/7793509-L.jpg',
    description: 'As Aventuras de Sherlock Holmes é uma coleção de doze contos escrita por Arthur Conan Doyle, publicada pela primeira vez em 14 de outubro de 1892. Contém os primeiros contos apresentando o detetive consultor Sherlock Holmes, os quais foram publicados em doze edições mensais da revista The Strand Magazine de julho de 1891 a junho de 1892.',
    genre: 'Mistério',
    publicationYear: '1892',
    language: 'Inglês',
    pageCount: 339
  },
  { 
    id: '4', 
    title: 'Jane Eyre', 
    author: 'Charlotte Brontë', 
    image: 'https://covers.openlibrary.org/b/id/7866048-L.jpg',
    description: 'Jane Eyre é um romance da escritora inglesa Charlotte Brontë, publicado sob o pseudônimo "Currer Bell", em 16 de outubro de 1847, pela editora Smith, Elder & Co., de Londres. A primeira edição americana foi publicada no ano seguinte pela Harper & Brothers de Nova Iorque. Jane Eyre é um romance de formação que narra as experiências da heroína homônima, incluindo seu crescimento até a idade adulta e seu amor por Mr. Rochester, o senhor sombrio de Thornfield Hall.',
    genre: 'Ficção Gótica',
    publicationYear: '1847',
    language: 'Inglês',
    pageCount: 610
  },
  { 
    id: '5', 
    title: 'O Retrato de Dorian Gray', 
    author: 'Oscar Wilde', 
    image: 'https://covers.openlibrary.org/b/id/7952251-L.jpg',
    description: 'O Retrato de Dorian Gray é um romance gótico e filosófico de Oscar Wilde, publicado pela primeira vez na revista Lippincott\'s Monthly Magazine em julho de 1890. Temendo que a história fosse indecente, o editor da revista eliminou aproximadamente quinhentas palavras antes da publicação, sem o conhecimento de Wilde. Apesar da censura, O Retrato de Dorian Gray ofendeu a sensibilidade moral dos críticos literários britânicos, alguns dos quais afirmaram que Oscar Wilde merecia ser processado por violar as leis que guardavam a moral pública. Em resposta, Wilde defendeu agressivamente seu romance e a arte em correspondência com a imprensa britânica.',
    genre: 'Ficção Gótica',
    publicationYear: '1890',
    language: 'Inglês',
    pageCount: 254
  },
  { 
    id: '6', 
    title: 'Frankenstein', 
    author: 'Mary Shelley', 
    image: 'https://covers.openlibrary.org/b/id/7973086-L.jpg',
    description: 'Frankenstein; ou, O Prometeu Moderno é um romance escrito pela autora inglesa Mary Shelley (1797–1851) que conta a história de Victor Frankenstein, um jovem cientista que cria uma criatura senciente em uma experiência científica não convencional. Shelley começou a escrever a história quando tinha 18 anos, e a primeira edição foi publicada anonimamente em Londres em 1 de janeiro de 1818. Seu nome apareceu pela primeira vez na segunda edição, publicada na França em 1823.',
    genre: 'Ficção Gótica',
    publicationYear: '1818',
    language: 'Inglês',
    pageCount: 280
  },
  { 
    id: '7', 
    title: 'Drácula', 
    author: 'Bram Stoker', 
    image: 'https://covers.openlibrary.org/b/id/7961534-L.jpg',
    description: 'Drácula é um romance epistolar de ficção gótica, escrito pelo autor irlandês Bram Stoker. Foi publicado pela primeira vez em 1897 e conta a história do Conde Drácula em sua tentativa de se mudar da Transilvânia para a Inglaterra, para disseminar a não-vida eterna à semelhança dos vampiros. O romance é conhecido por introduzir o personagem do professor Abraham Van Helsing e por sua descrição das origens e características do vampirismo, narrativas que definiram as principais tradições do gênero de fantasia gótica.',
    genre: 'Ficção Gótica',
    publicationYear: '1897',
    language: 'Inglês',
    pageCount: 488
  },
  { 
    id: '8', 
    title: 'Cem Anos de Solidão', 
    author: 'Gabriel García Márquez', 
    image: 'https://covers.openlibrary.org/b/id/7891527-L.jpg',
    description: 'Cem Anos de Solidão é uma obra do escritor colombiano Gabriel García Márquez, Prêmio Nobel de Literatura de 1982. É considerada uma das obras mais importantes da literatura do século XX. O romance conta a história da família Buendía ao longo de várias gerações no fictício vilarejo de Macondo, fundado por José Arcadio Buendía e Úrsula Iguarán.',
    genre: 'Realismo Mágico',
    publicationYear: '1967',
    language: 'Espanhol',
    pageCount: 471
  },
  { 
    id: '9', 
    title: 'A Metamorfose', 
    author: 'Franz Kafka', 
    image: 'https://covers.openlibrary.org/b/id/7851507-L.jpg',
    description: 'A Metamorfose (Die Verwandlung, no original em alemão) é uma novela escrita por Franz Kafka, publicada pela primeira vez em 1915. A obra conta a história de Gregor Samsa, um caixeiro-viajante que acorda certa manhã metamorfoseado num inseto gigante não identificado.',
    genre: 'Ficção Absurda',
    publicationYear: '1915',
    language: 'Alemão',
    pageCount: 44
  },
  { 
    id: '10', 
    title: 'A Montanha Mágica', 
    author: 'Thomas Mann', 
    image: 'https://covers.openlibrary.org/b/id/7977159-L.jpg',
    description: 'A Montanha Mágica é um romance escrito pelo autor alemão Thomas Mann, publicado pela primeira vez em 1924. É amplamente considerado como um dos romances mais influentes do século XX. O enredo segue a estadia do jovem engenheiro civil Hans Castorp em uma sanatório nos Alpes suíços, chamado Berghof, devido a uma visita de três semanas ao seu primo doente. A estadia de Castorp é estendida indefinidamente quando é diagnosticado com tuberculose.',
    genre: 'Ficção Filosófica',
    publicationYear: '1924',
    language: 'Alemão',
    pageCount: 976
  },
  { 
    id: '11', 
    title: 'O Processo', 
    author: 'Franz Kafka', 
    image: 'https://covers.openlibrary.org/b/id/8030282-L.jpg',
    description: 'O Processo (Der Prozess, no original em alemão) é um romance inacabado escrito por Franz Kafka e publicado postumamente em 1925. A obra é frequentemente considerada uma das mais influentes do século XX. O enredo segue Josef K., um homem que é preso e processado pelo sistema jurídico sem que lhe seja informada a causa ou os detalhes específicos de seu crime.',
    genre: 'Ficção Absurda',
    publicationYear: '1925',
    language: 'Alemão',
    pageCount: 255
  },
  { 
    id: '12', 
    title: 'O Estrangeiro', 
    author: 'Albert Camus', 
    image: 'https://covers.openlibrary.org/b/id/7856409-L.jpg',
    description: 'O Estrangeiro (L\'Étranger, no original em francês) é um romance do autor francês Albert Camus, publicado em 1942. É uma das obras mais famosas e amplamente lidas de Camus. A história segue Meursault, um argelino-francês que comete um assassinato sem motivo aparente, levando a eventos que exploram temas de absurdo, indiferença e alienação.',
    genre: 'Ficção Absurda',
    publicationYear: '1942',
    language: 'Francês',
    pageCount: 123
  },
  { 
    id: '13', 
    title: 'Grande Sertão: Veredas', 
    author: 'João Guimarães Rosa', 
    image: 'https://covers.openlibrary.org/b/id/7977369-L.jpg',
    description: 'Grande Sertão: Veredas é um romance do escritor brasileiro João Guimarães Rosa, publicado em 1956. A história é contada pelo jagunço Riobaldo, que narra suas experiências no sertão de Minas Gerais, suas lutas, amores e confrontos com o bando liderado pelo chefe Joca Ramiro.',
    genre: 'Ficção Regionalista',
    publicationYear: '1956',
    language: 'Português',
    pageCount: 525
  },
  { 
    id: '14', 
    title: 'Ensaio Sobre a Cegueira', 
    author: 'José Saramago', 
    image: 'https://covers.openlibrary.org/b/id/8012699-L.jpg',
    description: 'Ensaio Sobre a Cegueira é um romance do autor português José Saramago, publicado em 1995. A história se passa em uma cidade não identificada, onde as pessoas inexplicavelmente começam a ficar cegas e são colocadas em quarentena. O livro explora temas como a sociedade, a natureza humana e a resiliência.',
    genre: 'Ficção Distópica',
    publicationYear: '1995',
    language: 'Português',
    pageCount: 312
  },
  { 
    id: '15', 
    title: 'Cemitério de Pássaros', 
    author: 'Danielle Steel', 
    image: 'https://covers.openlibrary.org/b/id/8012914-L.jpg',
    description: 'Cemitério de Pássaros é um romance da autora norte-americana Danielle Steel, publicado em 1981. A história segue a vida de Melanie, uma jovem que supera desafios pessoais e traumas enquanto luta pela felicidade e realiza seus sonhos.',
    genre: 'Romance Contemporâneo',
    publicationYear: '1981',
    language: 'Inglês',
    pageCount: 432
  },
  { 
    id: '16', 
    title: 'Dom Quixote', 
    author: 'Miguel de Cervantes', 
    image: 'https://covers.openlibrary.org/b/id/7887558-L.jpg',
    description: 'Dom Quixote é um romance do autor espanhol Miguel de Cervantes, publicado em duas partes em 1605 e 1615. É considerado uma das obras mais importantes da literatura espanhola e universal. A história segue Alonso Quixano, um fidalgo que enlouquece após ler muitos livros de cavalaria e decide se tornar um cavaleiro andante, adotando o nome de Dom Quixote.',
    genre: 'Sátira',
    publicationYear: '1605 e 1615',
    language: 'Espanhol',
    pageCount: 863
  },
  { 
    id: '17', 
    title: 'Guerra e Paz', 
    author: 'Lev Tolstói', 
    image: 'https://covers.openlibrary.org/b/id/7876413-L.jpg',
    description: 'Guerra e Paz é um romance do autor russo Lev Tolstói, publicado entre 1865 e 1869. É uma das obras mais extensas da literatura mundial e uma das mais importantes da literatura russa. A narrativa segue as vidas de cinco aristocratas russos e suas famílias durante as Guerras Napoleônicas.',
    genre: 'Romance Histórico',
    publicationYear: '1869',
    language: 'Russo',
    pageCount: 1225
  },
  { 
    id: '18', 
    title: '1984', 
    author: 'George Orwell', 
    image: 'https://covers.openlibrary.org/b/id/7989838-L.jpg',
    description: '1984 é um romance distópico do autor britânico George Orwell, publicado em 1949. A história se passa em um regime totalitário onde o governo exerce controle absoluto sobre a vida dos cidadãos. O protagonista, Winston Smith, trabalha no Ministério da Verdade e se rebela contra o sistema opressivo.',
    genre: 'Ficção Distópica',
    publicationYear: '1949',
    language: 'Inglês',
    pageCount: 328
  },
  { 
    id: '19', 
    title: 'A Revolução dos Bichos', 
    author: 'George Orwell', 
    image: 'https://covers.openlibrary.org/b/id/7852575-L.jpg',
    description: 'A Revolução dos Bichos (Animal Farm, no original em inglês) é uma fábula política do autor britânico George Orwell, publicada em 1945. O livro usa um grupo de animais que se rebelam contra seus donos humanos como uma alegoria para os eventos que levaram à Revolução Russa de 1917 e os primeiros anos do regime soviético.',
    genre: 'Sátira Política',
    publicationYear: '1945',
    language: 'Inglês',
    pageCount: 112
  },
  { 
    id: '20', 
    title: 'O Pequeno Príncipe', 
    author: 'Antoine de Saint-Exupéry', 
    image: 'https://covers.openlibrary.org/b/id/7986811-L.jpg',
    description: 'O Pequeno Príncipe (Le Petit Prince, no original em francês) é um livro do autor francês Antoine de Saint-Exupéry, publicado em 1943. É um dos livros mais traduzidos e vendidos do mundo. A história é narrada por um piloto que faz um pouso de emergência no deserto do Saara e encontra um jovem príncipe que viaja entre planetas.',
    genre: 'Conto Filosófico',
    publicationYear: '1943',
    language: 'Francês',
    pageCount: 96
  },
  { 
    id: '21', 
    title: 'O Hobbit', 
    author: 'J.R.R. Tolkien', 
    image: 'https://covers.openlibrary.org/b/id/7930421-L.jpg',
    description: 'O Hobbit (The Hobbit, no original em inglês) é um romance de fantasia do autor britânico J.R.R. Tolkien, publicado em 1937. A história segue Bilbo Bolseiro, um hobbit que é arrastado em uma aventura épica para recuperar o tesouro guardado pelo dragão Smaug. Ele é acompanhado por um grupo de anões e Gandalf, o mago.',
    genre: 'Fantasia',
    publicationYear: '1937',
    language: 'Inglês',
    pageCount: 310
  },
  { 
    id: '22', 
    title: 'A Divina Comédia', 
    author: 'Dante Alighieri', 
    image: 'https://covers.openlibrary.org/b/id/7935588-L.jpg',
    description: 'A Divina Comédia é uma obra épica do autor italiano Dante Alighieri, escrita no início do século XIV e concluída em 1320, pouco antes de sua morte. É amplamente considerada uma das maiores obras da literatura mundial. A narrativa segue Dante em sua jornada pelo Inferno, Purgatório e Paraíso, guiado pelo poeta romano Virgílio e pela amada Beatriz.',
    genre: 'Épico',
    publicationYear: '1320',
    language: 'Italiano',
    pageCount: 798
  },
  { 
    id: '23', 
    title: 'O Médico', 
    author: 'Noah Gordon', 
    image: 'https://covers.openlibrary.org/b/id/7851589-L.jpg',
    description: 'O Médico (The Physician, no original em inglês) é um romance histórico do autor norte-americano Noah Gordon, publicado em 1986. A história segue a jornada de Rob J. Cole, um jovem órfão inglês com um talento extraordinário para a medicina, enquanto ele viaja pela Europa em busca de conhecimento e experiência.',
    genre: 'Romance Histórico',
    publicationYear: '1986',
    language: 'Inglês',
    pageCount: 736
  },
  { 
    id: '24', 
    title: 'Maus', 
    author: 'Art Spiegelman', 
    image: 'https://covers.openlibrary.org/b/id/7862344-L.jpg',
    description: 'Maus é uma graphic novel do autor norte-americano Art Spiegelman, publicada em dois volumes em 1986 e 1991. É uma das obras mais aclamadas do gênero. A história é uma narrativa biográfica em forma de quadrinhos, que retrata a experiência do autor e seu pai durante o Holocausto, usando animais antropomórficos para representar diferentes grupos étnicos.',
    genre: 'História em Quadrinhos',
    publicationYear: '1986-1991',
    language: 'Inglês',
    pageCount: 296
  },
  { 
    id: '25', 
    title: 'Crime e Castigo', 
    author: 'Fiódor Dostoiévski', 
    image: 'https://covers.openlibrary.org/b/id/7893886-L.jpg',
    description: 'Crime e Castigo é um romance do autor russo Fiódor Dostoiévski, publicado pela primeira vez em 1866. É uma das obras mais importantes da literatura russa e mundial. A história segue Rodion Raskólnikov, um ex-estudante que comete um assassinato e lida com as consequências psicológicas e morais.',
    genre: 'Ficção Psicológica',
    publicationYear: '1866',
    language: 'Russo',
    pageCount: 551
  },
  { 
    id: '26', 
    title: 'O Sol é para Todos', 
    author: 'Harper Lee', 
    image: 'https://covers.openlibrary.org/b/id/7888505-L.jpg',
    description: 'O Sol é para Todos (To Kill a Mockingbird, no original em inglês) é um romance da autora norte-americana Harper Lee, publicado em 1960. É um clássico da literatura americana contemporânea. A história é narrada pela jovem Scout Finch e aborda temas de racismo e injustiça em uma pequena cidade do sul dos Estados Unidos.',
    genre: 'Ficção Social',
    publicationYear: '1960',
    language: 'Inglês',
    pageCount: 323
  },
  { 
    id: '27', 
    title: 'O Nome do Vento', 
    author: 'Patrick Rothfuss', 
    image: 'https://covers.openlibrary.org/b/id/7855201-L.jpg',
    description: 'O Nome do Vento (The Name of the Wind, no original em inglês) é um romance de fantasia do autor norte-americano Patrick Rothfuss, publicado em 2007. É o primeiro livro da trilogia Crônica do Matador do Rei. A história é narrada pelo personagem Kvothe e segue suas aventuras e busca pelo conhecimento em um mundo de magia e segredos.',
    genre: 'Fantasia',
    publicationYear: '2007',
    language: 'Inglês',
    pageCount: 662
  },
  { 
    id: '28', 
    title: 'O Senhor dos Anéis', 
    author: 'J.R.R. Tolkien', 
    image: 'https://covers.openlibrary.org/b/id/7891525-L.jpg',
    description: 'O Senhor dos Anéis (The Lord of the Rings, no original em inglês) é uma trilogia de fantasia épica do autor britânico J.R.R. Tolkien, publicada entre 1954 e 1955. A narrativa segue a jornada de um grupo de personagens em um mundo fictício na tentativa de destruir um poderoso anel mágico e derrotar o Senhor Sombrio Sauron.',
    genre: 'Fantasia Épica',
    publicationYear: '1954-1955',
    language: 'Inglês',
    pageCount: 1216
  },
  { 
    id: '29', 
    title: 'O Caçador de Pipas', 
    author: 'Khaled Hosseini', 
    image: 'https://covers.openlibrary.org/b/id/7886985-L.jpg',
    description: 'O Caçador de Pipas (The Kite Runner, no original em inglês) é um romance do autor afegão Khaled Hosseini, publicado em 2003. A história é narrada por Amir, um afegão que cresce em meio às transformações políticas de seu país, e explora temas de amizade, redenção e a busca por perdão.',
    genre: 'Ficção Contemporânea',
    publicationYear: '2003',
    language: 'Inglês',
    pageCount: 400
  },
  { 
    id: '30', 
    title: 'O Leão, a Feiticeira e o Guarda-Roupa', 
    author: 'C.S. Lewis', 
    image: 'https://covers.openlibrary.org/b/id/7891523-L.jpg',
    description: 'O Leão, a Feiticeira e o Guarda-Roupa (The Lion, the Witch and the Wardrobe, no original em inglês) é o primeiro livro da série As Crônicas de Nárnia, escrita pelo autor britânico C.S. Lewis e publicada em 1950. A história segue quatro crianças que descobrem um mundo mágico ao entrar em um guarda-roupa e se envolvem em uma batalha entre o bem e o mal.',
    genre: 'Literatura Infantojuvenil',
    publicationYear: '1950',
    language: 'Inglês',
    pageCount: 208
  },
    { 
      id: '31', 
      title: 'A Culpa é das Estrelas', 
      author: 'John Green', 
      image: 'https://covers.openlibrary.org/b/id/7891400-L.jpg',
      description: 'A Culpa é das Estrelas é um romance do autor norte-americano John Green, publicado em 2012. A história segue Hazel Grace Lancaster, uma adolescente com câncer, que se apaixona por Augustus Waters, um rapaz que também enfrenta a doença. Juntos, eles embarcam em uma jornada de amor e descobertas.',
      genre: 'Drama Adolescente',
      publicationYear: '2012',
      language: 'Inglês',
      pageCount: 336
    },
    { 
      id: '32', 
      title: 'Se Eu Ficar', 
      author: 'Gayle Forman', 
      image: 'https://covers.openlibrary.org/b/id/7864421-L.jpg',
      description: 'Se Eu Ficar (If I Stay, no original em inglês) é um romance da autora norte-americana Gayle Forman, publicado em 2009. A história gira em torno de Mia Hall, uma adolescente que sofre um acidente de carro que muda completamente sua vida. Em meio à tragédia, ela precisa decidir se vai continuar lutando pela vida ou se deixará partir.',
      genre: 'Drama Adolescente',
      publicationYear: '2009',
      language: 'Inglês',
      pageCount: 288
    },
    { 
      id: '33', 
      title: 'Os 13 Porquês', 
      author: 'Jay Asher', 
      image: 'https://covers.openlibrary.org/b/id/7891584-L.jpg',
      description: 'Os 13 Porquês (Thirteen Reasons Why, no original em inglês) é um romance do autor norte-americano Jay Asher, publicado em 2007. A história é narrada por Clay Jensen, um jovem que recebe uma série de fitas gravadas pela colega Hannah Baker, que cometeu suicídio. Nas fitas, ela explica as razões que a levaram a essa decisão.',
      genre: 'Drama Adolescente',
      publicationYear: '2007',
      language: 'Inglês',
      pageCount: 288
    },
    { 
      id: '34', 
      title: 'Extraordinário', 
      author: 'R.J. Palacio', 
      image: 'https://covers.openlibrary.org/b/id/7862350-L.jpg',
      description: 'Extraordinário (Wonder, no original em inglês) é um romance da autora norte-americana R.J. Palacio, publicado em 2012. A história segue August Pullman, um menino com uma deformidade facial que enfrenta os desafios de se encaixar em uma nova escola e lidar com o preconceito e a aceitação.',
      genre: 'Drama Adolescente',
      publicationYear: '2012',
      language: 'Inglês',
      pageCount: 410
    },
    { 
      id: '35', 
      title: 'Quem é Você, Alasca?', 
      author: 'John Green', 
      image: 'https://covers.openlibrary.org/b/id/7864432-L.jpg',
      description: 'Quem é Você, Alasca? (Looking for Alaska, no original em inglês) é um romance do autor norte-americano John Green, publicado em 2005. A história segue Miles Halter, um adolescente que se muda para um colégio interno e se envolve com Alasca Young, uma garota enigmática. O livro explora temas como amor, perda e descobertas pessoais.',
      genre: 'Drama Adolescente',
      publicationYear: '2005',
      language: 'Inglês',
      pageCount: 256
    },
    { 
      id: '36', 
      title: 'Antes de Partir', 
      author: 'Colleen Oakley', 
      image: 'https://covers.openlibrary.org/b/id/7862317-L.jpg',
      description: 'Antes de Partir (Before I Go, no original em inglês) é um romance da autora norte-americana Colleen Oakley, publicado em 2015. A história segue Daisy Richmond, uma jovem que vence um câncer, mas descobre que seu marido está determinado a encontrar uma nova esposa para cuidar de sua filha após a sua eventual recaída.',
      genre: 'Drama Adolescente',
      publicationYear: '2015',
      language: 'Inglês',
      pageCount: 320
    },
    { 
      id: '37', 
      title: 'Cidades de Papel', 
      author: 'John Green', 
      image: 'https://covers.openlibrary.org/b/id/7864482-L.jpg',
      description: 'Cidades de Papel (Paper Towns, no original em inglês) é um romance do autor norte-americano John Green, publicado em 2008. A história segue Quentin Jacobsen, um jovem que parte em uma jornada para encontrar Margo Roth Spiegelman, sua enigmática vizinha e paixão platônica, que desaparece deixando pistas para ele.',
      genre: 'Drama Adolescente',
      publicationYear: '2008',
      language: 'Inglês',
      pageCount: 305
    },
    { 
      id: '38', 
      title: 'Em Algum Lugar nas Estrelas', 
      author: 'Clare Vanderpool', 
      image: 'https://covers.openlibrary.org/b/id/7862336-L.jpg',
      description: 'Em Algum Lugar nas Estrelas (Navigating Early, no original em inglês) é um romance da autora norte-americana Clare Vanderpool, publicado em 2013. A história segue Jack Baker, um adolescente que embarca em uma jornada ao lado de Early Auden para encontrar uma constelação perdida, em uma narrativa que mistura amizade, perda e autodescoberta.',
      genre: 'Drama Adolescente',
      publicationYear: '2013',
      language: 'Inglês',
      pageCount: 351
    },
    { 
      id: '39', 
      title: 'Cartas de Amor aos Mortos', 
      author: 'Ava Dellaira', 
      image: 'https://covers.openlibrary.org/b/id/7862316-L.jpg',
      description: 'Cartas de Amor aos Mortos (Love Letters to the Dead, no original em inglês) é um romance da autora norte-americana Ava Dellaira, publicado em 2014. A história é contada através de cartas escritas por Laurel para figuras icônicas que faleceram jovens, enquanto ela lida com o luto pela morte de sua irmã mais velha.',
      genre: 'Drama Adolescente',
      publicationYear: '2014',
      language: 'Inglês',
      pageCount: 327
    },
    { 
      id: '40', 
      title: 'Tudo, Tudo... E Nós', 
      author: 'Nicola Yoon', 
      image: 'https://covers.openlibrary.org/b/id/7862377-L.jpg',
      description: 'Tudo, Tudo... E Nós (Everything, Everything, no original em inglês) é um romance da autora norte-americana Nicola Yoon, publicado em 2015. A história segue Madeline Whittier, uma adolescente que vive isolada devido a uma condição médica rara, mas sua vida muda quando um novo vizinho, Olly Bright, entra em sua vida.',
      genre: 'Drama Adolescente',
      publicationYear: '2015',
      language: 'Inglês',
      pageCount: 320
    },  
    {
      id: '41',
      title: 'As Vantagens de Ser Invisível',
      author: 'Stephen Chbosky',
      image: 'https://covers.openlibrary.org/b/id/7990300-L.jpg',
      description: 'O livro narra as experiências de Charlie, um adolescente introvertido que enfrenta os desafios do ensino médio, amizades e descobertas pessoais. Uma história sensível sobre aceitação e crescimento.',
      genre: 'Drama Adolescente',
      publicationYear: '1999',
      language: 'Inglês',
      pageCount: 213
    },
    {
      id: '42',
      title: 'Eleanor & Park',
      author: 'Rainbow Rowell',
      image: 'https://covers.openlibrary.org/b/id/7894267-L.jpg',
      description: 'Eleanor & Park é uma história de amor entre dois jovens desajustados que encontram consolo um no outro. O livro aborda temas como amizade, família e a busca por identidade.',
      genre: 'Drama Adolescente',
      publicationYear: '2012',
      language: 'Inglês',
      pageCount: 328
    },
    {
      id: '43',
      title: 'A Culpa É das Estrelas',
      author: 'John Green',
      image: 'https://covers.openlibrary.org/b/id/7897340-L.jpg',
      description: 'A Culpa É das Estrelas é um romance que conta a história de Hazel Grace e Gus, dois adolescentes que se conhecem em um grupo de apoio a pacientes com câncer. A trama aborda temas como amor, amizade e a busca por significado na vida.',
      genre: 'Drama Adolescente',
      publicationYear: '2012',
      language: 'Inglês',
      pageCount: 318
    },
    {
      id: '44',
      title: 'Extraordinário',
      author: 'R.J. Palacio',
      image: 'https://covers.openlibrary.org/b/id/7897429-L.jpg',
      description: 'Extraordinário segue a jornada de Auggie Pullman, um menino com uma deformidade facial que enfrenta o desafio de frequentar a escola pela primeira vez. O livro aborda temas de aceitação, empatia e autoaceitação.',
      genre: 'Drama Adolescente',
      publicationYear: '2012',
      language: 'Inglês',
      pageCount: 315
    },
    {
      id: '45',
      title: 'O Ódio Que Você Semeia',
      author: 'Angie Thomas',
      image: 'https://covers.openlibrary.org/b/id/7883663-L.jpg',
      description: 'O Ódio Que Você Semeia acompanha Starr Carter, uma adolescente que testemunha o assassinato de seu amigo por um policial. O livro aborda questões de racismo, violência policial e ativismo.',
      genre: 'Drama Adolescente',
      publicationYear: '2017',
      language: 'Inglês',
      pageCount: 464
    },
    {
      id: '46',
      title: 'Simon vs. A Agenda Homo Sapiens',
      author: 'Becky Albertalli',
      image: 'https://covers.openlibrary.org/b/id/7892456-L.jpg',
      description: 'Simon vs. A Agenda Homo Sapiens é uma comédia romântica que segue Simon Spier, um adolescente gay que se apaixona por um colega anônimo da escola. O livro aborda temas de identidade, amizade e aceitação.',
      genre: 'Drama Adolescente',
      publicationYear: '2015',
      language: 'Inglês',
      pageCount: 303
    },
    {
      id: '47',
      title: 'Cidades de Papel',
      author: 'John Green',
      image: 'https://covers.openlibrary.org/b/id/7897387-L.jpg',
      description: 'Cidades de Papel segue Quentin Jacobsen em uma jornada para encontrar Margo Roth Spiegelman, sua enigmática vizinha que desaparece. O livro explora temas de amizade, busca de identidade e aventura.',
      genre: 'Drama Adolescente',
      publicationYear: '2008',
      language: 'Inglês',
      pageCount: 305
    },
    {
      id: '48',
      title: 'Quem É Você, Alasca?',
      author: 'John Green',
      image: 'https://covers.openlibrary.org/b/id/7897358-L.jpg',
      description: 'Quem É Você, Alasca? segue Miles Halter em sua jornada para encontrar o significado de sua vida em um colégio interno. Ele se envolve com a enigmática Alasca Young. O livro aborda temas de amizade, amor e perda.',
      genre: 'Drama Adolescente',
      publicationYear: '2005',
      language: 'Inglês',
      pageCount: 256
    },
    {
      id: '49',
      title: 'Deixe a Neve Cair',
      author: 'John Green, Maureen Johnson, Lauren Myracle',
      image: 'https://covers.openlibrary.org/b/id/7897343-L.jpg',
      description: 'Deixe a Neve Cair é uma coletânea de três contos de Natal interligados, escritos por três autores diferentes. Os contos exploram temas de amor, amizade e a magia do Natal.',
      genre: 'Drama Adolescente',
      publicationYear: '2008',
      language: 'Inglês',
      pageCount: 352
    },
    {
      id: '50',
      title: 'A Hospedeira',
      author: 'Stephenie Meyer',
      image: 'https://covers.openlibrary.org/b/id/7892446-L.jpg',
      description: 'A Hospedeira é um romance de ficção científica que segue a história de Melanie Stryder, uma das últimas humanas lutando contra uma invasão alienígena. Quando Melanie é capturada, uma alienígena chamada Peregrina é implantada em seu corpo. No entanto, a personalidade de Melanie permanece viva e as duas compartilham um corpo. Juntas, elas embarcam em uma jornada para encontrar o homem que amam. O livro explora temas de identidade, amor e sobrevivência.',
      genre: 'Drama Adolescente',
      publicationYear: '2008',
      language: 'Inglês',
      pageCount: 619
    },
    {
      id: '51',
      title: 'A Ilha do Tesouro',
      author: 'Robert Louis Stevenson',
      image: 'https://covers.openlibrary.org/b/id/7993323-L.jpg',
      description: 'A Ilha do Tesouro é um clássico da literatura de aventura que segue as perigosas aventuras do jovem Jim Hawkins em busca de um tesouro enterrado. O livro é repleto de piratas, mapas do tesouro e reviravoltas emocionantes.',
      genre: 'Aventura',
      publicationYear: '1883',
      language: 'Inglês',
      pageCount: 311
    },
    {
      id: '52',
      title: 'As Minas de Salomão',
      author: 'H. Rider Haggard',
      image: 'https://covers.openlibrary.org/b/id/7961090-L.jpg',
      description: 'As Minas de Salomão é um clássico da literatura de aventura que segue a expedição liderada por Allan Quatermain em busca das lendárias minas do rei Salomão. A jornada é repleta de perigos, descobertas e emoções intensas.',
      genre: 'Aventura',
      publicationYear: '1885',
      language: 'Inglês',
      pageCount: 352
    },
    {
      id: '53',
      title: 'Viagem ao Centro da Terra',
      author: 'Júlio Verne',
      image: 'https://covers.openlibrary.org/b/id/7985409-L.jpg',
      description: 'Viagem ao Centro da Terra é um clássico da ficção científica e aventura que segue as explorações do Professor Otto Lidenbrock e seu sobrinho Axel. Eles embarcam em uma jornada extraordinária para o interior da Terra, encontrando paisagens e criaturas surpreendentes.',
      genre: 'Aventura',
      publicationYear: '1864',
      language: 'Francês',
      pageCount: 259
    },
    {
      id: '54',
      title: 'O Último dos Moicanos',
      author: 'James Fenimore Cooper',
      image: 'https://covers.openlibrary.org/b/id/7890692-L.jpg',
      description: 'O Último dos Moicanos é um clássico da literatura americana que se passa durante a Guerra Franco-Indígena. O livro segue as aventuras de Hawkeye, um fronteiriço, e seus amigos enquanto enfrentam os perigos da guerra e os desafios da natureza selvagem.',
      genre: 'Aventura',
      publicationYear: '1826',
      language: 'Inglês',
      pageCount: 434
    },
    {
      id: '55',
      title: 'A Volta ao Mundo em 80 Dias',
      author: 'Júlio Verne',
      image: 'https://covers.openlibrary.org/b/id/7997622-L.jpg',
      description: 'A Volta ao Mundo em 80 Dias é um clássico da literatura de aventura que segue as incríveis façanhas de Phileas Fogg, um cavalheiro inglês que aposta que pode dar a volta ao mundo em 80 dias. A história é uma emocionante corrida contra o tempo cheia de desafios inesperados.',
      genre: 'Aventura',
      publicationYear: '1872',
      language: 'Francês',
      pageCount: 212
    },
    {
      id: '56',
      title: 'Cem Anos de Solidão',
      author: 'Gabriel García Márquez',
      image: 'https://covers.openlibrary.org/b/id/7997374-L.jpg',
      description: 'Cem Anos de Solidão é uma obra-prima do realismo mágico que narra a história da família Buendía em Macondo, uma cidade fictícia na Colômbia. A narrativa é rica em elementos mágicos e fantásticos, criando um universo surreal e envolvente.',
      genre: 'Realismo Mágico',
      publicationYear: '1967',
      language: 'Espanhol',
      pageCount: 448
    },
    {
      id: '57',
      title: 'O Outono do Patriarca',
      author: 'Gabriel García Márquez',
      image: 'https://covers.openlibrary.org/b/id/7997376-L.jpg',
      description: 'O Outono do Patriarca é uma obra de realismo mágico que apresenta a vida e o governo de um ditador sem nome em um país caribenho. A narrativa se desenrola de forma não linear, explorando os delírios e a solidão do protagonista.',
      genre: 'Realismo Mágico',
      publicationYear: '1975',
      language: 'Espanhol',
      pageCount: 255
    },
    {
      id: '58',
      title: 'A Metamorfose',
      author: 'Franz Kafka',
      image: 'https://covers.openlibrary.org/b/id/7982884-L.jpg',
      description: 'A Metamorfose é uma novela que conta a história de Gregor Samsa, um vendedor que acorda transformado em um inseto gigante. A obra explora temas de alienação, responsabilidade e a natureza humana.',
      genre: 'Realismo Mágico',
      publicationYear: '1915',
      language: 'Alemão',
      pageCount: 49
    },
    {
      id: '59',
      title: 'A Insustentável Leveza do Ser',
      author: 'Milan Kundera',
      image: 'https://covers.openlibrary.org/b/id/7988371-L.jpg',
      description: 'A Insustentável Leveza do Ser é um romance filosófico que segue a vida de quatro personagens em meio às turbulências políticas na Tchecoslováquia e à invasão soviética. A obra explora questões de liberdade, amor e destino.',
      genre: 'Realismo Mágico',
      publicationYear: '1984',
      language: 'Francês',
      pageCount: 313
    },
    {
      id: '60',
      title: 'O Amor nos Tempos do Cólera',
      author: 'Gabriel García Márquez',
      image: 'https://covers.openlibrary.org/b/id/7997377-L.jpg',
      description: 'O Amor nos Tempos do Cólera é um romance que segue a história de amor entre Florentino Ariza e Fermina Daza, que se reencontram após anos separados. A narrativa é permeada pelo realismo mágico característico do autor.',
      genre: 'Realismo Mágico',
      publicationYear: '1985',
      language: 'Espanhol',
      pageCount: 368
    },
    {
      id: '61',
      title: 'O Espelho Mágico',
      author: 'Machado de Assis',
      image: 'https://covers.openlibrary.org/b/id/7909016-L.jpg',
      description: 'O Espelho Mágico é um conto de Machado de Assis que explora temas de ilusão e reflexão. A história segue um homem que encontra um espelho mágico capaz de mostrar o futuro, mas com consequências inesperadas.',
      genre: 'Realismo Mágico',
      publicationYear: '1882',
      language: 'Português',
      pageCount: 11
    },
    {
      id: '62',
      title: 'O Homem Duplicado',
      author: 'José Saramago',
      image: 'https://covers.openlibrary.org/b/id/7978700-L.jpg',
      description: 'O Homem Duplicado é um romance que segue a vida de Tertuliano Máximo Afonso, um professor que descobre a existência de um sósia seu. A obra explora questões de identidade e existência.',
      genre: 'Realismo Mágico',
      publicationYear: '2002',
      language: 'Português',
      pageCount: 334
    },
    {
      id: '63',
      title: 'Assim Falou Zaratustra',
      author: 'Friedrich Nietzsche',
      image: 'https://covers.openlibrary.org/b/id/7946406-L.jpg',
      description: 'Assim Falou Zaratustra é uma obra filosófica que apresenta as reflexões e ensinamentos do personagem Zaratustra. O livro aborda temas como o eterno retorno, a superação do homem e a busca pelo sentido da existência.',
      genre: 'Ficção Filosófica',
      publicationYear: '1883',
      language: 'Alemão',
      pageCount: 365
    },
    {
      id: '64',
      title: 'O Estrangeiro',
      author: 'Albert Camus',
      image: 'https://covers.openlibrary.org/b/id/7993449-L.jpg',
      description: 'O Estrangeiro é um romance que segue a história de Meursault, um homem apático e indiferente diante das convenções sociais. A obra levanta questões sobre a absurdez da existência e a natureza humana.',
      genre: 'Ficção Filosófica',
      publicationYear: '1942',
      language: 'Francês',
      pageCount: 123
    },
    {
      id: '65',
      title: 'A Náusea',
      author: 'Jean-Paul Sartre',
      image: 'https://covers.openlibrary.org/b/id/7993639-L.jpg',
      description: 'A Náusea é um romance filosófico que segue Antoine Roquentin, um escritor que experimenta uma profunda sensação de alienação e despersonalização. A obra explora temas de existencialismo e liberdade.',
      genre: 'Ficção Filosófica',
      publicationYear: '1938',
      language: 'Francês',
      pageCount: 178
    },
    {
      id: '66',
      title: 'Homem-Aranha: A Última Caçada de Kraven',
      author: 'J.M. DeMatteis, Mike Zeck',
      image: 'https://covers.openlibrary.org/b/id/7983426-L.jpg',
      description: 'Nesta história clássica do Homem-Aranha, o vilão Kraven, o Caçador, prepara uma armadilha mortal para o herói. Com reviravoltas sombrias e um confronto épico, esta é uma das sagas mais memoráveis do Aranha.',
      genre: 'História em Quadrinhos',
      publicationYear: '1987',
      language: 'Inglês',
      pageCount: 160
    },
    {
      id: '67',
      title: 'X-Men: Dias de um Futuro Esquecido',
      author: 'Chris Claremont, John Byrne',
      image: 'https://covers.openlibrary.org/b/id/7983427-L.jpg',
      description: 'Nesta icônica história dos X-Men, um futuro distópico assombrado por sentinelas assassinas leva os mutantes a uma batalha pela sobrevivência. Uma trama intensa e cheia de reviravoltas.',
      genre: 'História em Quadrinhos',
      publicationYear: '1981',
      language: 'Inglês',
      pageCount: 144
    },
    {
      id: '68',
      title: 'Demolidor: A Queda de Murdock',
      author: 'Brian Michael Bendis, Alex Maleev',
      image: 'https://covers.openlibrary.org/b/id/7997393-L.jpg',
      description: 'Nesta história do Demolidor, Matt Murdock enfrenta uma série de desafios pessoais e profissionais, levando-o ao limite. Uma narrativa intensa e envolvente sobre superação e redenção.',
      genre: 'História em Quadrinhos',
      publicationYear: '2003',
      language: 'Inglês',
      pageCount: 336
    },
    {
      id: '69',
      title: 'Os Vingadores: A Queda',
      author: 'Brian Michael Bendis, David Finch',
      image: 'https://covers.openlibrary.org/b/id/7997394-L.jpg',
      description: 'Nesta saga dos Vingadores, a equipe enfrenta uma crise que abala suas fundações. Com traições e confrontos épicos, a narrativa redefine o destino dos maiores heróis da Terra.',
      genre: 'História em Quadrinhos',
      publicationYear: '2004',
      language: 'Inglês',
      pageCount: 224
    },
    {
      id: '70',
      title: 'Thor: O Renascer dos Deuses',
      author: 'J. Michael Straczynski, Olivier Coipel',
      image: 'https://covers.openlibrary.org/b/id/7997395-L.jpg',
      description: 'Nesta história do Thor, o Deus do Trovão enfrenta uma ameaça de proporções cósmicas. Com uma narrativa épica e visuais deslumbrantes, o herói encara desafios divinos.',
      genre: 'História em Quadrinhos',
      publicationYear: '2008',
      language: 'Inglês',
      pageCount: 152
    },
    {
      id: '71',
      title: 'Batman: O Cavaleiro das Trevas',
      author: 'Frank Miller, Klaus Janson',
      image: 'https://covers.openlibrary.org/b/id/7997396-L.jpg',
      description: 'Nesta história icônica do Batman, Bruce Wayne retorna para combater o crime em uma Gotham City à beira do colapso. Uma narrativa sombria e influente que redefine o herói.',
      genre: 'História em Quadrinhos',
      publicationYear: '1986',
      language: 'Inglês',
      pageCount: 224
    },
    {
      id: '72',
      title: 'Superman: Entre a Foice e o Martelo',
      author: 'Mark Millar, Dave Johnson',
      image: 'https://covers.openlibrary.org/b/id/7997397-L.jpg',
      description: 'Nesta história alternativa, Superman nasce na União Soviética e se torna o símbolo do socialismo. Uma visão intrigante do Homem de Aço em um mundo divergente.',
      genre: 'História em Quadrinhos',
      publicationYear: '2003',
      language: 'Inglês',
      pageCount: 160
    },
    {
      id: '73',
      title: 'Mulher-Maravilha: Deuses e Mortais',
      author: 'George Pérez, Len Wein, Greg Potter',
      image: 'https://covers.openlibrary.org/b/id/7997398-L.jpg',
      description: 'Nesta reimaginação da origem da Mulher-Maravilha, a princesa amazona enfrenta desafios épicos ao deixar a ilha de Themyscira. Uma jornada de autodescoberta e heroísmo.',
      genre: 'História em Quadrinhos',
      publicationYear: '1987',
      language: 'Inglês',
      pageCount: 192
    },
    {
      id: '74',
      title: 'Liga da Justiça: Torre de Babel',
      author: 'Mark Waid, Howard Porter',
      image: 'https://covers.openlibrary.org/b/id/7997399-L.jpg',
      description: 'Nesta história da Liga da Justiça, os planos de contingência de Batman para deter cada membro da equipe caem nas mãos erradas. Uma trama de intriga e confrontos épicos.',
      genre: 'História em Quadrinhos',
      publicationYear: '2000',
      language: 'Inglês',
      pageCount: 208
    },
    {
      id: '75',
      title: 'Aquaman: O Trono de Atlântida',
      author: 'Geoff Johns, Ivan Reis',
      image: 'https://covers.openlibrary.org/b/id/7997400-L.jpg',
      description: 'Nesta saga do Aquaman, o herói enfrenta desafios para manter o trono de Atlântida. Uma narrativa que mergulha nas complexidades do reino submarino.',
      genre: 'História em Quadrinhos',
      publicationYear: '2012',
      language: 'Inglês',
      pageCount: 192
    },
    {
      id: '76',
      title: 'Turma da Mônica: Laços',
      author: 'Vitor Cafaggi, Lu Cafaggi',
      image: 'https://covers.openlibrary.org/b/id/7997401-L.jpg',
      description: 'Nesta aventura da Turma da Mônica, Mônica, Cebolinha, Magali e Cascão partem em busca de Floquinho, o cachorro do Cebolinha. Uma história emocionante de amizade e coragem.',
      genre: 'História em Quadrinhos',
      publicationYear: '2013',
      language: 'Português',
      pageCount: 82
    },
    {
      id: '77',
      title: 'Turma da Mônica: Lições',
      author: 'Vitor Cafaggi, Lu Cafaggi',
      image: 'https://covers.openlibrary.org/b/id/7997402-L.jpg',
      description: 'Nesta nova aventura da Turma da Mônica, os amigos enfrentam desafios e aprendizados na escola. Uma história sobre crescimento e amadurecimento.',
      genre: 'História em Quadrinhos',
      publicationYear: '2015',
      language: 'Português',
      pageCount: 82
    },
    {
      id: '78',
      title: 'Turma da Mônica: Lembranças',
      author: 'Vitor Cafaggi, Lu Cafaggi',
      image: 'https://covers.openlibrary.org/b/id/7997403-L.jpg',
      description: 'Nesta história da Turma da Mônica, os amigos relembram momentos especiais de suas vidas. Uma narrativa nostálgica e cheia de emoção.',
      genre: 'História em Quadrinhos',
      publicationYear: '2017',
      language: 'Português',
      pageCount: 82
    },
    {
      id: '79',
      title: 'Turma da Mônica: Vamos Fazer de Conta!',
      author: 'Vitor Cafaggi, Lu Cafaggi',
      image: 'https://covers.openlibrary.org/b/id/7997404-L.jpg',
      description: 'Nesta divertida aventura da Turma da Mônica, as crianças embarcam em uma jornada de imaginação e criatividade. Uma história que celebra a infância.',
      genre: 'História em Quadrinhos',
      publicationYear: '2019',
      language: 'Português',
      pageCount: 82
    },
    {
      id: '80',
      title: 'Turma da Mônica: Tudo Isto é Muito Estranho',
      author: 'Vitor Cafaggi, Lu Cafaggi',
      image: 'https://covers.openlibrary.org/b/id/7997405-L.jpg',
      description: 'Nesta história da Turma da Mônica, os amigos vivem situações inusitadas e engraçadas. Uma narrativa cheia de humor e surpresas.',
      genre: 'História em Quadrinhos',
      publicationYear: '2021',
      language: 'Português',
      pageCount: 82
    }
    
    
    
        
        
];

export default books;


